name:                fp-essence
version:             0.1.0.0
github:              "vaibhav276/fp-essence"
license:             BSD3
author:              "Vaibhav Pujari"
maintainer:          "276vaibhav+github@gmail.com"
copyright:           "2020 Vaibhav Pujari"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vaibhav276/fp-essence#readme>

dependencies:
- base >= 4.7 && < 5
- text == 1.2.3.1

library:
  source-dirs: src

executables:
  fp-essence-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-essence

tests:
  fp-essence-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp-essence
